### PR TITLE
add sandbox flag

### PR DESCRIPTION
**Pull request by FynnBe**
cc @jmetz

### CODE REVIEW

**Review by jmetz — COMMENTED** [review]
Looks like this PR is crossing streams a bit with the "add reviewer" PR, #27 

Not sure if a flag to use the sandbox is an ideal way to go here... is there not a cleaner mechanism to achieve this? Ideally just temporarily changing the `vars.S3_FOLDER` value. Would make this PR unnecessary.

**Comment by jmetz** [comment]
Looking at the `environments` feature of github - perhaps this should be used instead? https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

**Comment by FynnBe** [comment]
> Looks like this PR is crossing streams a bit with the "add reviewer" PR, #27
> 
> Not sure if a flag to use the sandbox is an ideal way to go here... is there not a cleaner mechanism to achieve this? Ideally just temporarily changing the `vars.S3_FOLDER` value. Would make this PR unnecessary.

yeah, sorry this PR should really have waited for #27 to be merged.. 
hmm. yeah, might be cleaner. but from the outside (a dispatch) can one select a different gh env??

**Comment by FynnBe** [comment]
looks like we'd still have an input flag, based on which we would then switch the gh env instead of the value of just S3_FOLDER... 
Maybe we can leave this for future improvements

**Comment by jmetz** [comment]
Yeah the alternative would be to have additional dispatches specifically for sandbox, instead of a flag.

Dunno which is cleaner 🤷‍♀️ - and whatever makes most sense to you is what we should go with as you're the one who's going to be working with this for the next while anyway!

**Comment by FynnBe** [comment]
for now I like the flag, mostly because it's done now and because we have a lot of wfs already. 
If we ever want to change two variables for 'sandbox' mode we should opt for a gh env and have separate dispatch workflows.

**Pull request merged**
