### PR TITLE
Add biapy checks

### PR DESCRIPTION
**Pull request by FynnBe**

### CODE REVIEW

**Comment by FynnBe** [comment]
JTLYK, maybe the split in #77 allows you @danifranco to use the `upload_reports.py` script

**Comment by danifranco** [comment]
Sorry for the delay: I've been updating BiaPy and releasing a new version containing an updated code to import (both `v4_0` and `v5_0`), finetune and export models before doing this. I've just completed `check_compatibility_biapy.py` script with a function inside BiaPy that checks each model compatibility. Let me know what do you thing (you know that I'm not very familiarized with CI so maybe I missed something). 

A few things to comment:
- I'm not really sure the purpose of ``upload_reports.py`` so I don't know if I really need it...
- For instance segmentation workflows, I need to know where to place/read what is representing each channel, so I can create the final instances afterwards using a post-processing such as marker controlled watershed, multicut, agglomeration etc. For example: foreground + contour, foreground + contour + distances etc. As I told you, we can use the name convention we are following in BiaPy, but it can be other (we just need to stablish one). I'm not sure where to start the discussion on this topic so I leave it here so you can, please, point me the best place. Will describe more the name convention we are using in BiaPy in detail in that discussion.

**Comment by FynnBe** [comment]
> For instance segmentation workflows, I need to know where to place/read what is representing each channel, so I can create the final instances afterwards using a post-processing such as marker controlled watershed, multicut, agglomeration etc. For example: foreground + contour, foreground + contour + distances etc. As I told you, we can use the name convention we are following in BiaPy, but it can be other (we just need to stablish one). I'm not sure where to start the discussion on this topic so I leave it here so you can, please, point me the best place. Will describe more the name convention we are using in BiaPy in detail in that discussion.


For now just follow your own biapy convention with the names. We can have an initial discussion about standardizing this in a wednesday meeting. To prepare that you can start an issue or a discussion over at https://github.com/bioimage-io/spec-bioimage-io

**Comment by danifranco** [comment]
I opened [an issue](https://github.com/bioimage-io/spec-bioimage-io/issues/621) to discuss that. Regarding this PR, @FynnBe, can you explain me the purpose or `upload_reports.py`? Apart from that, I don't know if this PR can be merged or not: just tell me if I need to do somethign else please. Thank you so much!

**Comment by FynnBe** [comment]
I extracted `upload_reports.py` such that the environment that creates the reports does not need to have the `bioimageio_collection_backoffice` dependency that is then doing the upload.. 
Your script is fine as is -- there are no dep clashes, so no need to upload the reports in a separate env.

**Pull request merged**
